name: release
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  "Create a Release":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create a Release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          args: ${{ secrets.args }}
