 name: release
 on: repository_dispatch
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: "create release"
         uses: elgohr/Github-Release-Action@master
         env:
           GITHUB_TOKEN: ${{ secrets.token }}
         with:
           args: ${{ secrets.args }}
